version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    target-branch: "main"
    commit-message:
      prefix: "deps"
      prefix-development: "deps(dev)"
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@typescript-eslint/eslint-plugin"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@typescript-eslint/parser"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint-plugin-sonarjs"
        update-types: ["version-update:semver-major"]
