# These are supported funding model platforms

github: zavoloklom
patreon: zavoloklom
open_collective: zavoloklom
buy_me_a_coffee: zavoloklom
custom: [ "https://www.paypal.com/donate/?hosted_button_id=J8KS3RUFKSHDL", "https://boosty.to/zavoloklom" ]
